// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsalmsReading.Infrastructure.Data;

#nullable disable

namespace PsalmsReading.Infrastructure.Migrations
{
    [DbContext(typeof(PsalmsDbContext))]
    [Migration("20251223033423_MergePlannedIntoReadings")]
    partial class MergePlannedIntoReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PsalmsReading.Domain.Entities.PlannedReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PsalmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleApplied")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledDate", "PsalmId")
                        .IsUnique();

                    b.ToTable("PlannedReadings");
                });

            modelBuilder.Entity("PsalmsReading.Domain.Entities.Psalm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVerses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Psalms");
                });

            modelBuilder.Entity("PsalmsReading.Domain.Entities.ReadingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateRead")
                        .HasColumnType("TEXT");

                    b.Property<int>("PsalmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleApplied")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PsalmId", "DateRead")
                        .IsUnique();

                    b.ToTable("ReadingRecords");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.Epigraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Epigraphs");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.PsalmEpigraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpigraphId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PsalmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpigraphId");

                    b.HasIndex("PsalmId", "EpigraphId")
                        .IsUnique();

                    b.ToTable("PsalmEpigraphs");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.PsalmTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PsalmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.HasIndex("PsalmId", "ThemeId")
                        .IsUnique();

                    b.ToTable("PsalmThemes");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.PsalmEpigraph", b =>
                {
                    b.HasOne("PsalmsReading.Infrastructure.Entities.Epigraph", "Epigraph")
                        .WithMany("PsalmEpigraphs")
                        .HasForeignKey("EpigraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsalmsReading.Domain.Entities.Psalm", "Psalm")
                        .WithMany()
                        .HasForeignKey("PsalmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epigraph");

                    b.Navigation("Psalm");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.PsalmTheme", b =>
                {
                    b.HasOne("PsalmsReading.Domain.Entities.Psalm", "Psalm")
                        .WithMany()
                        .HasForeignKey("PsalmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PsalmsReading.Infrastructure.Entities.Theme", "Theme")
                        .WithMany("PsalmThemes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psalm");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.Epigraph", b =>
                {
                    b.Navigation("PsalmEpigraphs");
                });

            modelBuilder.Entity("PsalmsReading.Infrastructure.Entities.Theme", b =>
                {
                    b.Navigation("PsalmThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
